[project]
name = "video-dub"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "faster-whisper>=1.2.1",
    "imageio[ffmpeg]>=2.37.2",
    "nvidia-cublas-cu12>=12.9.1.4",
    "nvidia-cudnn-cu12>=9.18.1.3",
    "ollama>=0.6.1",
]
